// The embed configuration panel's schema. It lives here rather than in
// ConfigurationTab so the history slider can reuse each key's label without
// importing that component — and so a new toggle is labelled in both places at once.
export const CONFIG_SCHEMA = [
  {
    key: "showHomeButton",
    type: "toggle",
    label: "Show Home Button",
    description: "Show the home navigation button",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showHistory",
    type: "toggle",
    label: "Show History",
    description: "Display conversation history",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showConfigType",
    type: "toggle",
    label: "Show Config Type",
    description: "Show configuration type indicators",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showAdvancedParameters",
    type: "toggle",
    label: "Show Advanced Parameters",
    description: "Display advanced parameters",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showAdvancedConfigurations",
    type: "toggle",
    label: "Show Advanced Configurations",
    description: "Display advanced configurations",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showFallbackModel",
    type: "toggle",
    label: "Show Fallback Model",
    description: "Display the fallback model section",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showPreTool",
    type: "toggle",
    label: "Show Pre Tool",
    description: "Display pre tool",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showPromptHelper",
    type: "toggle",
    label: "Show Prompt Helper",
    description: "Show prompt helper button",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showResponseType",
    type: "toggle",
    label: "Show Response Type",
    description: "Show response type",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showVariables",
    type: "toggle",
    label: "Show Variables",
    description: "Show variables",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showAgentName",
    type: "toggle",
    label: "Show Agent Name",
    description: "Show agent name",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showPlayground",
    type: "toggle",
    label: "Show Playground",
    description: "Show the playground",
    defaultValue: true,
    section: "Interface Options",
  },
  {
    key: "showTestcases",
    type: "toggle",
    label: "Show Test Cases",
    description: "Display test cases tab in the embedded interface",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "slide",
    type: "select",
    label: "Slide Position",
    description: "Choose where GTWY appears on screen",
    defaultValue: "right",
    options: [
      { value: "left", label: "Left" },
      { value: "right", label: "Right" },
      { value: "full", label: "Full" },
    ],
    section: "Display Settings",
  },
  {
    key: "defaultOpen",
    type: "toggle",
    label: "Default Open",
    description: "Open GTWY automatically on page load",
    defaultValue: false,
    section: "Display Settings",
  },
  {
    key: "showFullScreenButton",
    type: "toggle",
    label: "Show Full Screen",
    description: "Show the full screen toggle button",
    defaultValue: true,
    section: "Display Settings",
    dependsOn: "showHeader",
  },
  {
    key: "showCloseButton",
    type: "toggle",
    label: "Show Close Button",
    description: "Show the close button",
    defaultValue: true,
    section: "Display Settings",
    dependsOn: "showHeader",
  },
  {
    key: "showHeader",
    type: "toggle",
    label: "Show Header",
    description: "Show the header section",
    defaultValue: true,
    section: "Display Settings",
  },
  {
    key: "addDefaultApiKeys",
    type: "toggle",
    label: "Add Default ApiKeys",
    description: "Add default api keys",
    defaultValue: false,
    section: "Display Settings",
  },
  {
    key: "layout",
    type: "select",
    label: "Config Panel Layout",
    description: "Choose how the Prompt/Model/Connectors/Memory/Settings panel is arranged for embed users",
    defaultValue: "tabs",
    options: [
      { value: "tabs", label: "Tabs" },
      { value: "single", label: "Single Page" },
      { value: "accordion", label: "Accordion" },
      { value: "stepper", label: "Guided Steps" },
    ],
    section: "Display Settings",
  },
  {
    key: "themeMode",
    type: "select",
    label: "Theme Mode",
    description: "Choose the color theme for the embedded GTWY interface",
    defaultValue: "system",
    options: [
      { value: "system", label: "System" },
      { value: "light", label: "Light" },
      { value: "dark", label: "Dark" },
    ],
    section: "Display Settings",
  },
  {
    key: "showDeleteAgentOption",
    type: "toggle",
    label: "Show Delete Agent Option",
    description: "Show the delete agent option in the agent action menu",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showReviewAgent",
    type: "toggle",
    label: "Show Review Agent",
    description: "Display review agent settings",
    defaultValue: false,
    section: "Interface Options",
  },
  {
    key: "showMcp",
    type: "toggle",
    label: "Show MCP Servers",
    description: "Display MCP server configuration in the Connectors tab",
    defaultValue: false,
    section: "Interface Options",
  },
];
